language: python
python:
- "3.5"
env:
  - DJANGO_SETTINGS_MODULE=config.settings.travis

install:
  - "pip install -r requirements/pinned/travis.txt"
script:
  - "coverage run manage.py test"
after_success:
  - codecov